"""Add salman

Revision ID: 3e8ba40e9535
Revises: 2d1175e7060a
Create Date: 2019-05-21 12:41:50.546530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8ba40e9535'
down_revision = '2d1175e7060a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('salman', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'salman')
    # ### end Alembic commands ###
