class constants(object):
    INVALID_TOKEN = 'Invalid or expire token'
    UPDATE_PASSWORD = 'The password successfully updated'
    INVALID_EMAIL_PASSWORD = 'Invalid email or password'
    REGISTER_SUCCESS = 'Register Successfully'
    LOGIN_SUCCESS = 'Login Successfully'
    POST_SUCCESS = 'Your post is now live!'
    UPDATE_SUCCESS = 'Update Successfully'
    DELETE_SUCCESS = 'Delete Successfully'
    FIRST_REGISTER_EMAIL = 'This email does not exist please first register with this email'
    EMAIL_ALREADY_EXIST = 'This email is already exist please choose another email'
    USER_ALREADY_EXIST = 'This user is already exist please choose another email'
    YOU_CAN_NOT_FOLLOW_YOURSELF = "You can not follow yourself"
    YOU_ARE_FOLLOWING = "You are following"
    THE_LINK_IS_NOT_FOLLOWING_BY_YOU = "This link is not following by you"
    YOUR_POST_IS_LIVE_NOW = "Your app is live now"
    MESSAGE_SEND = "Your message has been sent"
    POST = 'POST'
    GET = 'GET'
